#!/bin/bash

# Check argument count
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 {deps|cuda|linux|cuda_custom|driver|examples|llama.cpp|diffusion|llamafactory|vllm|sglang}"
	exit 1
fi

case "$1" in
	deps)
		echo "Running deps logic..."
		sudo apt install flex bison cmake libssl-dev libelf-dev libcurl4-openssl-dev python3-pip python3-venv
		;;
	cuda)
		echo "Running cuda logic..."
		mkdir -p cuda_deb
		for file in $(ls cuda); do cat cuda/${file}/part_* > cuda_deb/${file}.deb; done
		pushd cuda_deb
		sudo dpkg -i $(ls)
		popd
		;;
	linux)
		echo "Running linux logic..."
		cp configs/config-gcgroup-seoul-l4 linux/.config
		pushd linux
		make olddefconfig && make -j`nproc` && sudo make modules_install -j`nproc` && sudo make install
		popd
		;;
	cuda_custom)
		echo "Running cuda_custom logic..."
		pushd cuda_custom
		make EXTRA_CXXFLAGS="-I/usr/local/cuda-12.9/targets/x86_64-linux/include"
		popd
		;;
	driver)
		echo "Running driver logic..."
		pushd open-gpu-kernel-modules
		make -j`nproc`
		popd

		pushd open-gpu-kernel-modules/kernel-open
		sudo rmmod nvidia_uvm
		sudo rmmod nvidia_drm
		sudo rmmod nvidia_modeset
		sudo rmmod nvidia
		popd

		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/platform/x86/wmi.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/acpi/video.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/gpu/drm/ttm/ttm.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/gpu/drm/drm_ttm_helper.ko

		pushd open-gpu-kernel-modules/kernel-open
		sudo insmod nvidia.ko
		sudo insmod nvidia-modeset.ko
		sudo insmod nvidia-drm.ko
		sudo insmod nvidia-uvm.ko
		popd

		sudo mknod -m 666 /dev/nvidia0 c 195 0
		sudo mknod -m 666 /dev/nvidiactl c 195 255
		sudo mknod -m 666 /dev/nvidia-modeset c 195 254
		sudo mknod -m 666 /dev/nvidia-uvm c 508 0
		sudo mknod -m 666 /dev/nvidia-uvm-tools c 508 1
		;;
	examples)
		echo "Running examples logic..."
		;;
	llama.cpp)
		echo "Running llama.cpp logic..."
		pushd playground/infer/llama.cpp
		cmake -B build
		cmake --build build --config Release
		popd
		;;
	diffusion)
		echo "Running diffusion logic..."
		if [ ! -d "playground/infer/venv/diffusion" ]; then
			pushd playground/infer/venv
			python3 -m venv diffusion
			popd
		fi
		source playground/infer/venv/diffusion/bin/activate
		pushd playground/infer/diffusion
		pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu129
		pip3 install diffusers
		pip3 install transformers
		pip3 install protobuf
		pip3 install sentencepiece
		pip3 install accelerate
		popd
		deactivate
		;;
	llamafactory)
		echo "Running llamafactory logic..."
		if [ ! -d "playground/train/venv/LLaMA-Factory" ]; then
			pushd playground/train/venv
			python3 -m venv LLaMA-Factory
			popd
		fi
		source playground/train/venv/LLaMA-Factory/bin/activate
		pushd playground/train/LLaMA-Factory
		pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu129
		pip3 install -e ".[torch,metrics]" --no-build-isolation
		popd
		deactivate
		;;
	vllm)
		echo "Running vllm logic..."
		if [ ! -d "playground/infer/venv/vllm" ]; then
			pushd playground/infer/venv
			python3 -m venv vllm
			popd
		fi
		source playground/infer/venv/vllm/bin/activate
		pushd playground/infer/vllm
		pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu129
		VLLM_USE_PRECOMPILED=1 pip install --editable .
		popd
		deactivate
		;;
	sglang)
		echo "Running sglang logic..."
		if [ ! -d "playground/infer/venv/sglang" ]; then
			pushd playground/infer/venv
			python3 -m venv sglang
			popd
		fi
		source playground/infer/venv/sglang/bin/activate
		pushd playground/infer/sglang/python
		pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu129
		pip3 install --editable .
		popd
		deactivate
		;;
	*)
		echo "Invalid argument: $1"
		echo "Usage: $0 {deps|cuda|linux|cuda_custom|driver|examples|llama.cpp|diffusion|llamafactory|vllm|sglang}"
		exit 1
		;;
esac
