#!/bin/bash

# Check argument count
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 {deps|cuda|linux|cuda_custom|driver|examples|llama.cpp|llamafactory|vllm}"
	exit 1
fi

case "$1" in
	deps)
		echo "Running deps logic..."
		sudo apt install flex bison libssl-dev libelf-dev
		;;
	cuda)
		echo "Running cuda logic..."
		mkdir -p cuda_deb
		for file in $(ls cuda); do cat cuda/${file}/part_* > cuda_deb/${file}.deb; done
		pushd cuda_deb
		sudo dpkg -i $(ls)
		popd
		;;
	linux)
		echo "Running linux logic..."
		cp configs/config-gcgroup-seoul-l4 linux/.config
		pushd linux
		make olddefconfig && make -j`nproc` && sudo make modules_install -j`nproc` && sudo make install
		popd
		;;
	cuda_custom)
		echo "Running cuda_custom logic..."
		pushd cuda_custom
		make EXTRA_CXXFLAGS="-I/usr/local/cuda-12.9/targets/x86_64-linux/include"
		popd
		;;
	driver)
		echo "Running driver logic..."
		pushd open-gpu-kernel-modules
		make -j`nproc`
		popd

		pushd open-gpu-kernel-modules/kernel-open
		sudo rmmod nvidia_uvm
		sudo rmmod nvidia_drm
		sudo rmmod nvidia_modeset
		sudo rmmod nvidia
		popd

		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/platform/x86/wmi.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/acpi/video.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/gpu/drm/ttm/ttm.ko
		sudo insmod /lib/modules/6.11.0-gcgroup+/kernel/drivers/gpu/drm/drm_ttm_helper.ko

		pushd open-gpu-kernel-modules/kernel-open
		sudo insmod nvidia.ko
		sudo insmod nvidia-modeset.ko
		sudo insmod nvidia-drm.ko
		sudo insmod nvidia-uvm.ko
		popd

		sudo mknod -m 666 /dev/nvidia0 c 195 0
		sudo mknod -m 666 /dev/nvidiactl c 195 255
		sudo mknod -m 666 /dev/nvidia-modeset c 195 254
		sudo mknod -m 666 /dev/nvidia-uvm c 508 0
		sudo mknod -m 666 /dev/nvidia-uvm-tools c 508 1
		;;
	examples)
		echo "Running examples logic..."
		;;
	llama.cpp)
		echo "Running llama.cpp logic..."
		;;
	llamafactory)
		echo "Running llamafactory logic..."
		;;
	vllm)
		echo "Running vllm logic..."
		;;
	*)
		echo "Invalid argument: $1"
		echo "Usage: $0 {deps|cuda|linux|driver|examples|llama.cpp|llamafactory|vllm}"
		exit 1
		;;
esac
